### PR TITLE
probable fix for G5API, unknown event fix

### PR DESCRIPTION
**Pull request by 39ma**
G5API can't accept events from PugSharp with error `"message": "Event undefined is not implemented."`
Added to JSON events. I think there are some mistakes because I am very bad at C# :)

### CODE REVIEW

**Comment by TheR00st3r** [comment]
Thank you for the pr.
I think this will not fix the problem. The event names are set hardcoded in the constructor of the event classes.

@MD-V will investigate this issue later today.

**Comment by Apfelwurm** [comment]
After looking into it, there is way more to fix at different placed, and if I understood it correctly, the events should already be in there, coming from the events model. Please be a bit patient in regards to the get5 compatibility, since we have to get our yearly event next weekend behind us, before we can really focus on that topic. We will most likely implement automated testing of our api against g5api, so we can really verify that everything works in the long run.

**Comment by 39ma** [comment]
> After looking into it, there is way more to fix at different placed, and if I understood it correctly, the events should already be in there, coming from the events model. Please be a bit patient in regards to the get5 compatibility, since we have to get our yearly event next weekend behind us, before we can really focus on that topic. We will most likely implement automated testing of our api against g5api, so we can really verify that everything works in the long run.

Thank you, I'm just testing what I can and learning as I go. I am sending you all my guesses and possible fixes to facilitate development.

**Comment by 39ma** [comment]
ah, I dont know why the branch updated also here, sry.

**Pull request closed without merging**
